=== mosahar20/copy_course_work/data/conf/actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
	
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/actions" elementFormDefault="qualified"
	xmlns:Q4="stendhal">
	
		<complexType name="actions" >
		<sequence>
			<element name="actions" type="Q4:Actions" />
		</sequence>
	</complexType>
	
	<complexType name="action">
		<sequence>
			<element name="actions" type="Q4:Action" minOccurs="0" maxOccurs="unbounded"/>
			<element name="type" type="Q4:typeType" />
			<element name="implementation" type="Q4:implementation"></element>
			<element name="attributes" type="Q4:Attributes" />
		</xsd:sequence>
		<xsd:attribute name="name" type="string" use="required"></attribute>
	</xsd:complexType>
	
	
	
	<complexType name="Attributes">
		<sequence>
		<element name="type" type="attribute-string" use = "required">
			</element>
		<element name="maxParameters" type="attribute-integer" use="required">
			</element>
		<element name="minParameters" type="attribute-integer" use="required">
			</element>
		<element name="target" type="attribute-string" use="optional">
			</element>
		<element name="zone" type="attribute-string" use="optional">
			</element>
		<element name="x" type="attribute-integer" use="optional">
			</element>
		<element name="y" type="attribute-integer" use="optional">
			</element>
		</sequence>
	</complexType> 


	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>
	

	
    <complexType name="attribute-string">
    	<attribute name="value" type="string" />
    </complexType>

    <complexType name="attribute-integer">
    	<attribute name="value" type="integer" />
    </complexType>

    <complexType name="attribute-float">
    	<attribute name="value" type="float" />
    </complexType>
	
</schema>

=== mosahar20/copy_course_work/data/conf/actions/teleportaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">


	<action name="teleport">
		<implementation class-name="games.stendhal.server.actions.admin.InvisibleAction" />
		<attributes>
			<type value = "teleport" />
	 		<maxParameters value = "4" />
	 		<minParameters value = "4" />
	 		<target value = "params[0]" />
	 		<zone value = "params[1]" />
	 		<x value = "params[2]" />
	 		<y value = "params[3]" />
		</attributes>

	</action>
</actions>
